import { createRequire } from "node:module"; import path from "node:path";
const require = createRequire(import.meta.url);
const puppeteer = require(path.join(process.env.APPDATA, "npm/node_modules/hyperframes/node_modules/puppeteer-core"));
const BASE = process.argv[2] || "http://localhost:8790";
const b = await puppeteer.launch({ executablePath: "C:/Program Files/Google/Chrome/Application/chrome.exe", headless: "new" });
const p = await b.newPage(); const errs = []; p.on("pageerror", (e) => errs.push(e.message));
await p.setViewport({ width: 1440, height: 900 });
await p.goto(BASE + "/book/", { waitUntil: "networkidle2" }); await p.evaluate(() => localStorage.clear()); await p.reload({ waitUntil: "networkidle2" }); await new Promise((r) => setTimeout(r, 700));
const st = () => p.evaluate(() => ({ total: document.querySelector(".qc-price b").textContent, lines: [...document.querySelectorAll(".qc-lines div")].map((d) => d.innerText.replace(/\s*\n\s*/g, " = ")), steps: [...document.querySelectorAll(".qc-step")].filter((s) => !s.hidden).map((s) => s.querySelector("h2").textContent), pressed: [...document.querySelectorAll(".choice[aria-pressed=true] b")].map((x) => x.textContent), notice: !document.querySelector("[data-only=notbkk]").hidden }));
const click = (sel) => p.evaluate((s) => document.querySelector(s).click(), sel);
await click("[data-preset=fasttrack]"); console.log("FT choice     ", JSON.stringify(await st()));
await p.evaluate(() => { const s = document.querySelector("[data-bind=airport]"); s.value = "don-mueang-dmk"; s.dispatchEvent(new Event("change")); }); console.log("switch to DMK ", JSON.stringify(await st()));
await click("[data-switch-bkk]"); console.log("back to BKK   ", JSON.stringify(await st()));
await click('[data-group=service][data-value=hourly]'); await p.evaluate(() => document.querySelectorAll("[data-bind=ft]")[0].click()); console.log("driver + FT   ", JSON.stringify(await st()));
console.log("WA has FT:", decodeURIComponent(await p.$eval(".qc-send", (a) => a.href)).includes("Fast-Track"));
await p.goto(BASE + "/", { waitUntil: "networkidle2" }); await new Promise((r) => setTimeout(r, 500));
await p.evaluate(() => document.querySelector('[data-qb=mode][data-v=airport]').click());
console.log("home airport  ", await p.evaluate(() => [document.querySelector(".qb-price b").textContent, document.querySelector(".qb-price small").textContent, document.querySelector(".qb-go").getAttribute("href")]));
await p.goto(BASE + "/services/airport-fast-track/", { waitUntil: "networkidle2" });
console.log("FT page book link:", await p.evaluate(() => document.querySelector('.aside a[href^="/book/"]').getAttribute("href")));
console.log("errors", errs); await b.close();
